### PR TITLE
Fix navmesh

### PR DESCRIPTION
**Pull request by SamuelllG**
this fix has to be two PRs, please approve

### CODE REVIEW

**Review by DavidPgl — APPROVED** [review]

**Review by inkompotato — CHANGES_REQUESTED** [review]
broken

**Comment by inkompotato** [comment]
> broken

image

**Comment by SamuelllG** [comment]
please approve jan ^^ we have to delete the navmesh, push it, and make a new one haha

**Comment by SamuelllG** [comment]
Since changing the navmesh file causes it to break because the binary file isn't merged correctly, we have to delete it, and create it again. You can't do this in one PR because it then git recognizes the files as changed and we have the same problem.
(When the two PRs are on master and you checkout the branch, I guess it will still be broken, so you have to delete your local navmesh asset file before. But I'm not sure with this one.)

**Comment by inkompotato** [comment]
you did update the navmesh in your previous PR #195 which worked

**Comment by SamuelllG** [comment]
Yes! I updated it to not use the height mesh

**Comment by SamuelllG** [comment]
Since we want the height mesh, that was a temporary solution

**Comment by inkompotato** [comment]
ok, lets try it, revert if it fails

**Review by inkompotato — APPROVED** [review]

**Pull request merged**
