### PR TITLE
create navmesh

### PR DESCRIPTION
**Pull request by SamuelllG**
Since changing the navmesh file causes it to break because the binary file isn't merged correctly, we have to delete it, and create it again. You can't do this in one PR because it then git recognizes the files as changed and we have the same problem.
(When the two PRs are on master and you checkout the branch, I guess it will still be broken, so you will probably have to delete your local navmesh asset file before pulling.)

### CODE REVIEW

**Review by Kaes3kuch3n — APPROVED** [review]

**Review by inkompotato — CHANGES_REQUESTED** [review]
not working

**Comment by SamuelllG** [comment]
Yep, you're right, then we have a bigger problem with git

**Comment by inkompotato** [comment]
plz revert previous merges

**Comment by SamuelllG** [comment]
Don't panic

**Pull request closed without merging**
