### PR TITLE
Level design v2

### PR DESCRIPTION
**Pull request by SamuelllG**
added prefabs, fixed prefabs, added brushes, added different types of brushes, leveldesign

GAMESCENE change ;)

### CODE REVIEW

**Comment by SamuelllG** [comment]
since 224 files were changed ... BrushLogic.cs, CustomBrush.cs and BrushEditor.cs should be reviewed code-wise

**Review by thuemmels — DISMISSED** [review]
very nice :D

**Review by DavidPgl — DISMISSED** [review]

**Comment by tobihoffmann** [comment]
spotted some under water forest areas:
https://i.imgur.com/SXzIyAz.png

**Comment by SamuelllG** [comment]
@tobihoffmann yep I saw it, but didn't want to move it (because it's a hidden landmark!) xD

**Comment by SamuelllG** [comment]
but if you want, I can move it 😭 or can we lower the water level a bit.. maybe ?

**Comment by tobihoffmann** [comment]
> but if you want, I can move it 😭 or can we lower the water level a bit.. maybe ?

waves would possibly touch the ground then. But i think its ok for now, we can polish the map at a later state if we want imo

**Comment by SamuelllG** [comment]
close this since this is merged in another branch.. hopefully no functionality missing ^^

**Pull request closed without merging**
